# Generated by Django 6.0.3 on 2026-05-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="beds",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="hospital",
            name="contact_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="hospital",
            name="facilities",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="location",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hospital",
            name="price_range",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="hospital",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name="hospital",
            name="specialties",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="type",
            field=models.CharField(
                choices=[("private", "Private"), ("government", "Government")],
                default="private",
                max_length=20,
            ),
        ),
    ]
