# Generated by Django 6.0.3 on 2026-05-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_doctor"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="hospitals/"),
        ),
    ]
