# Generated by Django 6.0.3 on 2026-05-12 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_appointment_labtest_labtestbooking"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabTestReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateTimeField(auto_now_add=True)),
                ("results", models.TextField()),
                ("summary", models.TextField(blank=True)),
                ("doctor_notes", models.TextField(blank=True)),
                (
                    "report_file",
                    models.FileField(blank=True, null=True, upload_to="lab_reports/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="core.labtestbooking",
                    ),
                ),
            ],
        ),
    ]
